## 通过Fegin消费服务

# 设置注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# 设置端口号
server:
  port: 8765
# 设置服务名称
spring:
  application:
    name: service-feign
## 打开断路器（Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开）
feign:
  hystrix:
    enabled: true