# 设置端口号
server:
  port: 8761
# 在默认情况下erureka server也是一个eureka client ,必须要指定一个 server
# eureka.client.registerWithEureka：false 和 eureka.client.fetchRegistry：false来表明自己是一个eureka server
# defaultZone 注册中心地址
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 设置服务名称
spring:
  application:
    name: eureka-server